### ISSUE TITLE
"compiling" but no window appears macOs + Blender 2.83 #2036

### ISSUE THREAD

**Issue by winniejo** [Kode/haxe_bin#3]
@RobDangerous , @RafaelOliveira , (send from Moritz Brückner to haxe-bin )  
On my macbook pro I am using Blender 2.8.3 and installed the add-on, went all fine.
When I push the play button (It announcing that) it is "compiling" for 4+ second and
then it stops but no additional window appears.

(See terminal error message bellow.)

I un-ticked the cache build option, refresh, etc, but It did not help.
What should i do?

p.s. I also like to check out the Blender 2.79 version but cant find it.

Thanks Be save.
Winn

Blender: 2.83.5
Armory: Armory add on latest version 30 nov 2020*
OS: MacOS 10.13.xx // (HighSierra)
Graphics card: Macbook pro AMD Radeon HD 6490M 500mb
CPU intel i7
======

Here is the error message its expecting macOs 10.15 Iam guessing
which My Macbook pro cannot run . My MBP is running macOs 10.13.

__________ [Armory] Compiling __________
Exporting Scene
Scene exported in 0.018412113189697266
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
Referenced from: /ArmorySDK//Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
Referenced from: /ArmorySDK//Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
Referenced from: /ArmorySDK/Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
Referenced from: /ArmorySDK/Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib

Haxe compiler error.
Finished in 10.868728160858154
ERROR: Build failed,

**Comment by RobDangerous** [comment]
Yes, it requires a newer version. Sorry but I do not have a macOS installation that can compile Haxe for an older version of macOS.

**Comment by winniejo** [comment]
@RobDangerous  I understand but there are a lot of user that dont jump to the latest version of Mac OS for a good reason, that is why Blender has Mac OS 10.13 as minimum requirement for example.
I am using Blender and hopefully the add-on Armory one day.

Stay save
Winn

**Comment by RobDangerous** [comment]
It's been like that for a while and so far I received two complaints about it. One of them was from a non-regular macOS user who then just upgraded his installation. So all the data I have so far points to this being very rare.
Also please note that I'm not part of the Armory team nor do I know anything about Blender.

**Comment by RobDangerous** [comment]
That said, 10.13 is much newer than I thought because I always get confused with macOS version numbers. Will have another look at my compilation setup.

**Comment by winniejo** [comment]
@RobDangerous 
I noticed that the mac os 2011 to 2017 security/architecture features are mostly the same
The security/architecture features crap for the last 2 Mac os versions 2018 to 2019 is a little 
different then the rest. In case you didn't know bellow is a link to download macOS installers.

Thnks for your work stay save
Winn

2019 // macOS 10.15    Catalina 	    	
2018 // macOS 10.14    Mojave 		        
 
2017 // macOS  10.13    High Sierra 	  
2016 // macOS  10.12    Sierra   		 	     
2015 // macOS 10.11     El Capitan  	    
2014 // macOS 10.10    Yosemite,,          
2013 // macOS  10.9     Mavericks,	    
2012 // macOS 10.8      Mountain Lion     
2011 // macOS 10.7      Lion 		       

Note To download Macos installers. 
If you need High Sierra its faster to use the  Sierra installer or even Maverick and
after instal  do a SW upgrade to High Sierra by your laptop or comp.
Be aware not to upgrade automaticly macos 10.15 :).  
https://support.apple.com/en-us/HT211683

**Comment by RobDangerous** [comment]
Downloading and installing an old macOS is not what I need help with, I need help with the nightmare that is installing homebrew and ocaml and then using that to compile Haxe.

**Comment by winniejo** [comment]
Yes that is tricky dont know about ocami or haxe, 
but I recently installed HomeBrew and 'ImageMagick on Macos 10.13 below is a sample of the terminal lines for Homebrew .
But installing imagemagick was such a pain so I unpacked Imagemagick and put the file in the proper directory bij hand :) / Command+Shift+Dot.

Dont know if that will help you with the rest.

=======
My-Mac:~ linter$  ruby -e "$(curl -fsSkL raw.github.com/mistydemeo/tigerbrew/go/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1

Press ENTER to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /usr/local
etc etc.

**Comment by RobDangerous** [comment]
No, that doesn't help. But it's cute, thanks.

**Comment by RobDangerous** [comment]
Hey, good news, official Haxe now has the same issue (HaxeFoundation/haxe#10110) so we can just wait around and grab their GitHub action changes once it's fixed.

**Comment by winniejo** [comment]
:)

**Comment by calderarchinuk** [comment]
Hey @RobDangerous, just wanted to ping you that issue is now resolved.

I'm doing a bit of testing with kha (not armory) on osx 10.13.6 and I'm seeing a similar error. I'm guessing it will also get fixed from this github action change.

**Comment by RobDangerous** [comment]
Now I'm confused - it's resolved but you see a similar error?

**Comment by calderarchinuk** [comment]
Sorry, I didn't see the commit yesterday morning. This is the error I was seeing:
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
Referenced from: /usr/local/lib/haxe/lib/kha/git/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib
```
Updating to the latest version on git fixed my issue. Thanks!

**Comment by RobDangerous** [comment]
Yay, glad this is fixed.
